import pytest
import math
from core.graph_engine import Graph
from core.models import ArbitrageOpportunity


# 1. ADD RATE TESTS

def test_add_rate_valid_data():
    """Tests if valid rate data is added to the graph with the correct logarithmic weight."""
    engine = Graph()
    rate = 2.0
    
    engine.add_rate("BTC", "USDT", rate)
    
    assert "BTC" in engine.currencies
    assert "USDT" in engine.currencies
    
    expected_weight = -math.log(rate)
    actual_weight = engine.graph["BTC"]["USDT"]
    assert math.isclose(actual_weight, expected_weight, rel_tol=1e-9)

@pytest.mark.parametrize("invalid_rate", [
    0.0,
    -10.5,
    float("inf"),
    float("nan")
])
def test_add_rate_ignores_invalid_rates(invalid_rate):
    """Tests if the engine is resilient to corrupted exchange data (Defensive Programming)."""
    engine = Graph()
    engine.add_rate("BTC", "USDT", invalid_rate)
    
    assert len(engine.currencies) == 0
    assert "BTC" not in engine.graph


# 2. INTERNAL HELPER FUNCTION TESTS

def test_calculate_profit():
    """Tests the logic of converting logarithmic weights back to a percentage profit."""
    engine = Graph()
    
    # Artificially build the graph without using add_rate to isolate profit calculation testing
    engine.graph = {
        "A": {"B": -math.log(2.0)},  # Multiplier x2
        "B": {"C": -math.log(3.0)},  # Multiplier x3
        "C": {"A": -math.log(0.5)}   # Multiplier x0.5
    }
    
    # Capital: 1 * 2.0 * 3.0 * 0.5 = 3.0. Profit = 200%
    path = ["A", "B", "C", "A"]
    profit = engine._calculate_profit(path)
    
    assert math.isclose(profit, 200.0, rel_tol=1e-5)

def test_retrieve_cycle():
    """Tests if the algorithm correctly reconstructs the path from the predecessors dictionary."""
    # Simulate the state of the predecessors dictionary generated by Bellman-Ford
    predecessors = {
        "A": "C",
        "B": "A",
        "C": "B"
    }
    
    # Start reconstruction from node 'C'
    cycle = Graph._retrieve_cycle("C", predecessors)
    
    # Reconstruction goes backwards and reverses the array, should yield the correct cycle
    assert cycle == ["C", "A", "B", "C"]

def test_rotate_cycle_success():
    """Tests if the cycle is correctly rotated to start with the specified currency."""
    path = ["C", "A", "B", "C"]
    
    # We want the cycle to start with 'A'
    rotated = Graph._rotate_cycle(path, "A")
    
    assert rotated == ["A", "B", "C", "A"]

def test_rotate_cycle_start_not_in_path():
    """Tests the behavior when the starting currency is not present in the found cycle."""
    path = ["C", "A", "B", "C"]
    rotated = Graph._rotate_cycle(path, "PLN")
    
    assert rotated is None


# 3. CORE ALGORITHM TESTS (bellman_ford)

def test_bellman_ford_returns_none_when_no_arbitrage():
    """Tests a balanced market scenario - no arbitrage opportunity should be found."""
    engine = Graph()
    
    # Efficient market: USDT -> BTC -> ETH -> USDT = 1.0 (0% profit)
    engine.add_rate("USDT", "BTC", 1.0 / 50000.0)
    engine.add_rate("BTC", "ETH", 20.0)
    engine.add_rate("ETH", "USDT", 2500.0)

    opportunity = engine.bellman_ford("USDT")
    assert opportunity is None

def test_bellman_ford_finds_arbitrage_opportunity():
    """Tests a market with a hidden opportunity (Happy Path) - the algorithm MUST find the profit."""
    engine = Graph()
    
    # Inefficient market: USDT -> BTC -> ETH -> USDT = 1.2 (20% profit)
    engine.add_rate("USDT", "BTC", 1.0 / 50000.0)
    engine.add_rate("BTC", "ETH", 20.0)
    engine.add_rate("ETH", "USDT", 3000.0)

    opportunity = engine.bellman_ford("USDT")
    
    assert isinstance(opportunity, ArbitrageOpportunity)
    assert opportunity.path == ["USDT", "BTC", "ETH", "USDT"]
    assert math.isclose(opportunity.expected_profit_pct, 20.0, rel_tol=1e-5)